"""add staged_changes table

Revision ID: 03850ca41888
Revises: f42f44d6e323
Create Date: 2026-05-14 18:05:19.899249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03850ca41888'
down_revision: Union[str, Sequence[str], None] = 'f42f44d6e323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staged_changes',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='syncactionkind'), nullable=False),
    sa.PrimaryKeyConstraint('address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staged_changes')
    # ### end Alembic commands ###
