"""Add domain and alias models

Revision ID: f42f44d6e323
Revises: 
Create Date: 2026-05-14 16:22:58.909246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42f44d6e323'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('aliases',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('local_part', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('destinations', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['domain'], ['domains.name'], ),
    sa.PrimaryKeyConstraint('address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aliases')
    op.drop_table('domains')
    # ### end Alembic commands ###
